### ISSUE TITLE
crash with leatest lodash 3.*

### ISSUE THREAD

**Issue by marlic7** [jwarkentin/node-monkey#31]
Please change dependencies in package.json:
from
```
"dependencies": {
    "lodash": "*",
    "socket.io": "0.9.x"
},
```
to
```
"dependencies": {
    "lodash": "2.4.1",
    "socket.io": "0.9.x"
},
```

crash appear after invoke http://127.0.0.1:50500 in browser, and log is:
```
/www/node/test/nomo$ node app.js 
   info  - socket.io started
------------------
NodeMonkey started
To inspect output, open a browser to: http://127.0.0.1:50500
------------------
 

http.js:977
      throw new TypeError('first argument must be a string or Buffer');
            ^
TypeError: first argument must be a string or Buffer
    at ServerResponse.OutgoingMessage.end (http.js:977:13)
    at Server.<anonymous> (/www/node/test/nomo/node_modules/node-monkey/index.js:205:13)
    at Manager.handleRequest (/www/node/test/nomo/node_modules/node-monkey/node_modules/socket.io/lib/manager.js:588:28)
    at Server.<anonymous> (/www/node/test/nomo/node_modules/node-monkey/node_modules/socket.io/lib/manager.js:119:10)
    at Server.EventEmitter.emit (events.js:98:17)
    at HTTPParser.parser.onIncoming (http.js:2108:12)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
    at Socket.socket.ondata (http.js:1966:22)
    at TCP.onread (net.js:525:27)
```

**Comment by jwarkentin** [comment]
Sorry it took so long for me to get to this. The fix is published as node-monkey v0.2.14. Thanks for reporting the bug!
