### ISSUE TITLE
nomo.stop() throws error

### ISSUE THREAD

**Issue by JacopKane** [jwarkentin/node-monkey#33]
In short:
```javascript
this.iosrv.disconnect();
TypeError: undefined is not a function
```
Full output:

```javascript
info: socket.io started
------------------
NodeMonkey started
To inspect output, open a browser to: http://127.0.0.1:50500
------------------
 
/Users/furkantunali/Sites/_Sandbox/NOD-paths/node_modules/node-monkey/index.js:328
    this.iosrv.disconnect();
               ^
TypeError: undefined is not a function
    at NodeMonkey._.extend.stop (/Users/furkantunali/Sites/_Sandbox/NOD-paths/node_modules/node-monkey/index.js:328:16)
    at Object.<anonymous> (/Users/furkantunali/Sites/_Sandbox/NOD-paths/index.js:7:6)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
[Finished in 0.363s]
```

**Comment by jwarkentin** [comment]
That would only be able to happen if you called `stop()` without calling `start()` or if you called it twice in a row. Regardless, I just pushed a new version that shouldn't throw an error.
