### ISSUE TITLE
attachconsole is not a function

### ISSUE THREAD

**Issue by Gardezi1** [jwarkentin/node-monkey#43]
Hello, guys, first of all, awesome package. I don't what would I do without it. But I'm facing a problem and I can't understand what is it that I'm doing wrong since I'm following your documentation. Whenever I run my node application it crashes throwing this error: 

```
monkey.attachConsole();
       ^
TypeError: monkey.attachConsole is not a function
    at Object.<anonymous> (/home/contrive/tawseel-backend/main.js:8:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

here is my code which 

```
var monkey = require('node-monkey');
monkey.attachConsole();

```

**Comment by jwarkentin** [comment]
The documentation could make this more clear but the require call provides a function you must call (and optionally pass in options) to instantiate it. In the quick usage example you'll notice an extra set of parenthesis to call the function. Try this instead:

```
var monkey = require('node-monkey')();
```

**Comment by jwarkentin** [comment]
The documentation has been updated to be more clear.
