### ISSUE TITLE
Cannot find module './build/Release/DTraceProviderBindings'

### ISSUE THREAD

**Issue by OleileiA** [jwarkentin/node-monkey#45]
I got this error, when i require it.
`const nodeMonkey = require('node-monkey');`

error:
`{ Error: Cannot find module './build/Release/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/cyw/Desktop/自学/KOA2-gitbook笔记/node_modules/dtrace-provider/dtrace-provider.js:18:23)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3) code: 'MODULE_NOT_FOUND' }
`
my node version is 8.4.
I tried many ways, but it didn't work.

**Comment by jwarkentin** [comment]
Odd. I just tested a fresh install with npm 5.4.2 and node 8.6.0 and had no problems. Do you have any other dependencies included that might cause a conflict? What OS are you using? What version of npm are you using and is this a fresh install or is there any chance you recently updated npm without doing a fresh `npm install` on your project? I've dealt with more than enough problems related to npm 5+ and this just kind of feels like it's related. Try updating npm (`npm i -g npm`), deleting all `node_modules` directories and then running `npm install` in the root of your project.

**Comment by OleileiA** [comment]
genius！when i reinstall node_modules, found there is a install error about dtrace-provider.
The Chinese dir name cause it. I change the name and it works.
but when i run the program, i got another problem, i'll start another issue for it.
thanks a lot.

**Comment by jwarkentin** [comment]
Glad it worked!
